canonical/traefik-k8s-operator

README.md, config.yaml, src/charm.py, tests/unit/test_charm.py
Introduce a `routing_mode` charm option, structured as an enumeration, that allows you to select how Traefik will generate routes:
* `path`: Traefik will use its externally-visible url and create a route for the requester that will be structure like:
`<external_url>/<requester_model_name>-<requester_application_name>-<requester-unit-index>`
For example, an ingress-per-unit provider with `http://foo` external URL, will provide to the unit `my-unit/2` in the `my-model` model the following URL:
`http://foo/my-model-my-unit-2`
* `subdomain`: Traefik will use its externally-visible url, and create a route for the requester that will be structure like:
`<protocol>://<requester_model_name>-<requester_application_name>-<requester-unit-index>.<external_hostname>:<port>/`
For example, an …
=> Implement routing_mode option

requirements.txt, src/charm.py, tests/unit/test_charm.py
1. SDI does not seem to handle correctly scale-down of units, and especially scale-to-zero.
2. Avoid writing out spurious routes when the requesters have not yet written their part od the data (unit_name, model, host), but traefik-k8s already receives a RelationChanged event that is "paired" to the RelationJoined event.
Various hardenings, mostly work-around for broken SDI behaviours.
The code seems to work well on actual Juju.
The unit tests, OTOH, are plenty borked.
The fix to check for _actual_ unit count in the relation rather than relying on the `is_ready` of SDI has broken the tests, as the Mocks of SDI do not seem to correctly create units...
Saboteur tests by adding relations with Prometheus, removing those relations, scaling Prometheus to 0, scaling Prometheus to n and then to …
=> Fix various bugs in ingress-per-unit

.gitignore, lib/charms/traefik_k8s/v0/ingress_per_unit.py, src/charm.py, tests/unit/test_charm.py, tests/unit/test_lib_helpers.py, tests/unit/test_lib_per_unit_provides.py, tests/unit/test_lib_per_unit_requires.py
Removed SDI dependency from v0/ingress_per_unit Provider/Requirer
Fixes https://github.com/canonical/traefik-k8s-operator/issues/24
=> Remove SDI dependency from ingress_per_unit

lib/charms/traefik_k8s/v0/ingress_per_unit.py, tests/unit/test_lib_helpers.py, tests/unit/test_lib_per_unit_requires.py
Lib was missing some typing and docstrings, had complex type signatures and redundant code paths.
A bit of polishing.
No (production) code paths should have been altered. Utests/itests should be enough.
Added types and return type annotations throughout.
=> Purge sdi polish

lib/charms/traefik_k8s/v0/ingress_per_unit.py, requirements.txt
Document the dependency of `ingress_per_unit` on the `jsonschema` package (which was transitively
imported by SDI with LIBPATCH 6 and below).
Provide more informative error message on the missing `jsonschema` dependency for charms using the `ingress_per_unit` library.
Some housekeeping on requirements.txt.
N/A
N/A
Document the dependency of `ingress_per_unit` on the `jsonschema` package (which was transitively
imported by SDI with LIBPATCH 6 and below).
=> Document ingress_per_unit lib dependencies

lib/charms/traefik_k8s/v0/ingress_per_unit.py, src/charm.py, tests/unit/test_charm.py, tests/unit/test_lib_helpers.py, tests/unit/test_lib_per_unit_provides.py, tests/unit/test_lib_per_unit_requires.py
The IngressRequest object is unnecessarily complicated and introduces a confusing layer of request/response mechanics that is hard to reason about.
Get rid of that object, replace the existing request/response terminology for 'publish' on the one and the other side.
Unittest
it depends on the purge-sdi-polish PR, base will change to main as soon as that PR is merged
Simplified the ingress-per-unit api and internals.
Fixes https://github.com/canonical/traefik-k8s-operator/issues/43
=> Remove Request/Response mechanism in ingress-per-unit

lib/charms/traefik_route_k8s/v0/traefik_route.py, metadata.yaml, src/charm.py, tests/unit/test_route.py
This PR adds an integration with the Traefik Route charm (cf. https://github.com/PietroPasotti/traefik-route-k8s-operator), enabling users to configure Traefik on a per-relation basis, overcoming the limitations of ingress-per-unit and ingress-per-app, making Traefik a lot more general.
The role of Traefik in this integration is very limited: it simply has to accept a yaml config file and write it to the folder where traefik will load it up. Therefore the changes to the charm codebase are rather limited.
Aside from running the utests, you can test this in combination with TraefikRoute and prometheus-k8s in a live deployment (itests pending).
juju deploy traefik-route-k8s --channel beta
- Added `traefik_route_k8s/v0/traefik_route.py` lib
- Added `traefik_route` integration in the Traefik …
=> add traefik-route endpoint

lib/charms/traefik_k8s/v0/ingress.py, lib/charms/traefik_route_k8s/v0/traefik_route.py, metadata.yaml, src/charm.py, tests/integration/conftest.py, tests/integration/test_charm.py, tests/integration/test_charm_ipa.py, tests/integration/test_charm_ipu.py, tests/unit/test_charm.py, tests/unit/test_lib_helpers.py, tests/unit/test_lib_per_app_provides.py, tests/unit/test_lib_per_app_requires.py, tox.ini
Removed SDI from ingress (per app)
See #37 
- Added integration tests for 
- ingress: spring-music
- ingress-per-unit: prometheus-k8s
The relation interface is compatible with older versions of `ingress`, but the API is different. Similarly to ingress-per-unit, the `request/response` language was stripped in favour of a more semantically close one. See #42 and #48
the Requirer has `ready` and `revoked` events: reflecting the fact that the only thing that can happen to ingress is: it can be provided (with a given url), or it can be revoked (i.e. the url is no longer available).
`ready` also includes when ingress was already ready; i.e. when the url has changed.
the Provider has now 'data_provided` and `data_removed` events, following a similar principle: either the requirer has published …
=> Purge SDI from ingress (per app)

lib/charms/traefik_k8s/v0/ingress.py, lib/charms/traefik_k8s/v0/ingress_per_unit.py
Bumped IPA and IPU libpatch versions following changes in the previous PRs.
- ingress is now at 0.6
- ingress-per-unit is now at 0.10
=> bumped lib versions

lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/traefik_k8s/v0/ingress.py, lib/charms/traefik_k8s/v0/ingress_per_unit.py, tests/unit/test_lib_per_app_provides.py, tests/unit/test_lib_per_app_requires.py, tests/unit/test_lib_per_unit_provides.py, tests/unit/test_lib_per_unit_requires.py
`bind_address` sometimes returns None, requires mocking for utests, and could be routable outside the cluster.
Crossref: [OPENG-785](https://warthogs.atlassian.net/browse/OPENG-785)
Use `socket.getfqdn` instead of `bind_address`.
NTA.
Integration tests.
Replace bind_address with fqdn.
=> Use fqdn instead of bind_address

metadata.yaml
Help JUJU fail earlier if one tries to deploy traefik-k8s on a VM cloud.
See: #62 
- added assumes: k8s-api
=> added k8s api assumes

lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, tests/integration/test_charm_ipa.py, tests/integration/test_charm_ipu.py
On relation-departed hooks, some charms (e.g. prometheus-k8s) attempt to unconditionally get the `url/urls` attrs of ipu/ipa requirer. That results in ModelError in the unguarded case in which we are in a relation departed hook or whenever 1) the relation is there 2) relation.app is not None but yet 3) we can't read the relation data anymore.
Guarded that case with a try/except clause.
Deploy with prom (this branch) (manually copy over the fixed ingress_per_unit.py from this PR)
-  Fixed bug in IPU/IPA where unguarded attempts to read "url/urls" during relation-departed hooks would raise uncaught ModelError
=> fixed departed hooks for ipu and ipa

.github/workflows/pull-request.yaml, .github/workflows/release-edge.yaml
Removed the `--model testing` and logdump action to make it easier to map local testing env to the CI's
=> removed --model arg in itests workflows

.github/workflows/pull-request.yaml, .github/workflows/release-edge.yaml, lib/charms/harness_extensions/v0/capture_events.py, lib/charms/observability_libs/v0/juju_topology.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, tests/unit/test_lib_per_unit_requires.py, tox.ini
Closes #79 .
- `self.ingress.url` was returning old (non-falsey) value even after relation and/or app was removed.
- Seems like relation data is not emptied out even when looking from within a relation broken event. This may be a juju feature rather than a bug though/
=> [IPU] Make sure `revoked` is emitted

src/charm.py, tests/unit/test_charm.py
Fixes #76.
- Block if hostname is invalid.
For COS Lite load test, traefik is interfering with the manual nginx ingress. To circumvent that I mistakenly tried to set a custom port as part of `external_hostname`. 
(Note: could address this is a separate PR by introducing an `external_port` config option.)
- utests
- deploy and `juju config external_hostname="withport:8080"` should block.
Block if hostname is invalid.
=> Block if hostname is invalid

lib/charms/traefik_k8s/v1/ingress.py, tests/unit/test_lib_per_app_requires.py
An IPA analogue to #80.
https://github.com/canonical/alertmanager-k8s-operator/pull/94
[IPA] Make sure `ingress.url` returns an up-to-date value
=> [IPA] Make sure `ingress.url` returns an up-to-date value

.github/workflows/pull-request.yaml, pyproject.toml, src/charm.py, tests/integration/conftest.py, tests/integration/helpers.py, tests/integration/test_traefik_deployed_after_metallb.py, tests/integration/test_traefik_deployed_before_metallb.py, tests/integration/testers/.gitignore, tests/unit/test_charm.py
This fixes an error when relating to route before configuring external_hostname. Instead, traefik will go to waiting status
=> waiting status on missing hostname

lib/charms/observability_libs/v0/juju_topology.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/traefik_route_k8s/v0/traefik_route.py, src/charm.py, tests/integration/conftest.py, tests/integration/test_charm.py, tests/integration/test_charm_ipa.py, tests/integration/test_charm_ipu.py, tests/integration/test_charm_tcp.py, tests/integration/test_traefik_deployed_after_metallb.py, tests/integration/test_traefik_deployed_before_metallb.py
It is not currently possible to forward `_external_host` as a "known" value back to `TraefikRouteRequirer` without calling private methods, making it unwieldy to inform `TraefikRouteProviders` what the `external_host` may be.
Make `_external_host` into `external_host`, and pass it as a constructor argument to `TraefikRouteProvider`
See this [grafana-k8s issue](https://github.com/canonical/grafana-k8s-operator/issues/143#event-7605411772), for example.
Increase the visibility of `_external_host`, update `traefik_route` libraries
=> Increase the visibility of `_external_host`

lib/charms/traefik_route_k8s/v0/traefik_route.py
Previously, if `traefik` was deployed prior to any `TraefikRouteProviders` and had already acquired an `external_host` (either via `config-set` or from the loadbalancer assigning an address), the comparison to `StoredState` would always be true, and it would not be updated, despite the remote end potentially not knowing what the value is.
When `TraefikRouteRequirer` is ready, send the external host over relation data.
Update `TraefikRoute` again so the external host is passed through on more update conditions
=> Update `TraefikRoute` again so the external host is passed through on more update conditions

.github/workflows/codeql-analysis.yml, .github/workflows/issues.yml, .github/workflows/promote.yaml, .github/workflows/pull-request.yaml, .github/workflows/release-edge.yaml, lib/charms/traefik_k8s/v1/ingress.py, src/charm.py, tox.ini
CI is outdated ([fails](https://github.com/canonical/traefik-k8s-operator/actions/runs/3594529878/jobs/6057922843)).
Use centralized CI like all other o11y repos.
NTA.
Make sure all tox envs are reflected in CI.
Centralize CI.
=> Centralize CI

lib/charms/traefik_k8s/v1/ingress.py, src/charm.py, tests/unit/test_charm.py
The indentation rules for `stripPrefix` for per-app ingress were incorrect, and inconsistent with per-unit ingressing.
Fix the indentation, so it works as expected.
As part of this, extract the "common" configuration block generation logic to a new function (only the actual `PathPrefix` and list of LB servers once "ingress" is reworked to no longer be only "ingress per leader, which is the only configured LB, whether intentionally or not") to avoid this kind of frustrating indentation error.
Rework the unit tests somewhat so the `*_per_app` tests _actually_ test per-app.
Finally, fix requirer-side fetching of `url` in IPA.
It's pretty annoying unintended behavior from Traefik that a value which is at the wrong level of indentation successfully parses, but does not apply, so long as it can …
=> Fix per-app middleware injection

src/prometheus_alert_rules/reload_failure.rule, src/prometheus_alert_rules/unit_unavailable.rule
This PR add a new alert rule and fix an older one
The new alert rule we are adding checks whether the traefik config reload fails or not.
Pack the charm, deploy and relate it with prometheus charm.
=> alert rules for self-monitoring

tests/integration/spellbook/cache.py
spellbook's `do_build` was naively assuming `charmcraft pack` would succeed.
Also changed tox.ini so that linting is only ran on `src/`, because I was getting errors from charm libs (not owned by traefik)
Wrapped the command in a try/catch that aborts on nonzero return codes, raising a helpful message.
Hope the CI passes
* fixed bug in spellbook cache
=> catch charmcraft pack errors in spellbook

tests/integration/spellbook/cache.py
- add an envvar to enable/disable spellbook caching
- use `charmcraft pack --format=json` instead of string-splitting stdout.
The CI will tell.
* minor updates to spellbook
=> spellbook embetterments

lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, pyproject.toml, tests/unit/test_charm.py, tests/unit/test_event_serializers.py, tests/unit/test_lib_per_app_provides.py, tests/unit/test_lib_per_unit_listen_to.py, tests/unit/test_lib_per_unit_requires.py
This PR fixes issues with the charm's tests on newer versions of `ops`. Currently ops is pinned to 1.5.2.
**Most of the failures are from changes in 1.5.3 (the latest 1.x version is 1.5.4).** Specifically:
* test_show_proxied_endpoints_action_no_relations previously had error
"'ConfigData' object does not support item assignment". This was
caused by canonical/operator#787 and the fix is to stop setting items
on Model.config._data directly. Do it with update_config, but
suppress the config-changed event it triggers.
* test_ingress_app_provider_relate_provide previosly had error
ops.model.RelationDataTypeError: relation data values must be strings, not <class 'bool'>
caused by canonical/operator#786 and the fix is to send string values
instead of Python bools (lowercase as these would be …
=> Fixes for newer versions of ops (1.5.4 and 2.0.0rc2)

lib/charms/traefik_k8s/v1/ingress_per_unit.py, tox.ini
Resolving `all((some, tuple))` or other is not a generator, is not lazily-evalutated, and will immediately throw an `AttributeError` at resolution if something cannot be found.
Use a comprehension to provide a generator, and short-circuit on the first failure.
See [this comment](https://github.com/canonical/grafana-k8s-operator/issues/165#issuecomment-1375436662), reported on Grafana, but in this library.
Guard for `relation.app = None` in `ingress_per_unit`. Move tox to 3.8
=> Fix missing relation app

lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py
Libraries got out of sync with the long lifecycle of the TLS patch. Make them right.
Reconcile library versions
=> Reconcile library versions

tests/integration/conftest.py, tests/integration/test_charm_ipa.py, tests/integration/test_charm_ipu.py
Integration tests for `ingress-per-app` and `ingress-per-unit` were validating that the ingress is present by calling `ping` with the `-p` flag and the port. The `-p` flag is not for specifying a port however, but to specify padding data to put in the payload of the `ICMP` packet.
Because the `metallb` configuration is using the local IP of the host running `microk8s`, it is expected to always answer to pings. Therefore, those tests were not testing anything.
This change replaces the `ping` with a direct socket, testing the TCP connectivity to the ingress port.
=> Fix has_ingress integration tests

lib/charms/traefik_k8s/v1/ingress_per_unit.py
When removing the application, in relation-broken, `relation.app.name` fails because `relaion.app` is None.
```
File "/var/lib/juju/agents/unit-prom-0/charm/lib/charms/traefik_k8s/v1/ingress_per_unit.py", line 804, in _urls_from_relation_data
if not relation.app and not relation.app.name:  # type: ignore
```
Replace `and` with `or`.
Fixes #149.
Fixes https://github.com/canonical/prometheus-k8s-operator/issues/460.
https://github.com/canonical/prometheus-k8s-operator/issues/460
1. Relate `prometheus` - `traefik`
2. Remove traefik.
3. (Before this fix you'd get the error)
=> Do not check app.name if app is None

tests/interface/test_ingress.py
The interface tester was missing a configuration key. We're using ingress v1, so we should test against v1.
=> Fixed version in interface tester configuration

lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, pyproject.toml, src/charm.py, tests/interface/conftest.py, tests/scenario/test_setup.py, tests/scenario/test_status.py, tests/unit/test_charm.py, tests/unit/test_lib_per_app_provides.py, tests/unit/test_route.py, tests/unit/test_tls_certificates.py, tox.ini
The **flake8** plugins we use are re-implemented in **ruff**, which is why they have been removed from the dependencies.
**isort** is enabled (and used when formatting) through the `I001` rule.
The "exclude list" has been updated to omit folders that **ruff** excludes by default.
Everything else is the same, the only difference being two new rules being ignored (which weren't checked before anyway): 
* `N818: Exception name should be named with an Error suffix`, which I excluded due to the big refactoring required for it;
* `RET504: Unnecessary variable assignment before return statement`, which we do everywhere as it increases readability.
=> use ruff instead of flake8

src/charm.py, tests/integration/conftest.py, tests/integration/test_charm_tcp.py, tests/integration/test_tcp_ipa_compatibility.py, tests/integration/test_tcp_ipu_compatibility.py, tests/integration/test_tls.py
Itests were relying on update-status.
Do not rely on update-status in itests.
NTA.
No functional changes. Passes locally. If passes in CI we're probably ok with this change.
Do not rely on update-status in itests.
=> Fix itests

src/charm.py
This PR fix https://github.com/canonical/traefik-k8s-operator/issues/179
Now we use fqdn rather than IP
=> metrics endpoint generated using fqdn

tests/scenario/test_setup.py, tests/scenario/test_status.py, tests/scenario/test_workload_version.py, tox.ini
tests migrated to scenario 4.0
Wait to merge until https://github.com/canonical/ops-scenario/pull/39/files merges
=> scenario 4 compat

lib/charms/traefik_k8s/v2/ingress.py, tests/scenario/test_ingress_per_app.py
now that ingress requirer also expose unit data, we need to remove a leader guard preventing auto-data from being published on joined and changed without charm intervention.
Fixes a bug discovered by @gregory-schiano
=> removed leader guard

src/charm.py, tests/scenario/utils.py
Getting 404 when related charms set `redirect_https=True` but effective scheme is `http`.
Condition rendering the https-redirect middleware on the scheme.
Relate trfk - am and curl the traefik ingress url.
Render https-redirect middleware only if scheme is https.
=> Render https-redirect middleware only if scheme is https

lib/charms/traefik_k8s/v1/ingress_per_unit.py, src/charm.py, tests/scenario/utils.py
Fixes #219.
Tandem PRs:
- https://github.com/canonical/prometheus-k8s-operator/pull/508
Add `scheme ` to IPU following the implementation made in `ingress v2`.
=> add https scheme support to IPU loadBalancer

lib/.wokeignore, lib/charms/certificate_transfer_interface/v0/certificate_transfer.py, metadata.yaml, src/charm.py
The mutual_tls relation has been renamed.
This PR depends on:
- https://github.com/canonical/self-signed-certificates-operator/pull/22
Fetch-lib.
Fixes #223.
- End-to-end TLS.
- #204 
Relate ca - traefik - alertmanager - ca, and confirm curl works.
Replace mutual_tls with certificate_transfer.
=> Replace mutual_tls with certificate_transfer

lib/charms/certificate_transfer_interface/v0/certificate_transfer.py, lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, requirements.txt, src/charm.py
Update the use of the certificate-transfer library, after https://github.com/canonical/certificate-transfer-interface/issues/5 is fixed.
=> use new certificate-transfer library version

lib/charms/traefik_k8s/v2/ingress.py
The IPA library does not have a `scheme` arg in its manual updater, `provide_ingress_requirements`.
Repeat #232, this time for IPA.
Addresses https://github.com/canonical/karma-k8s-operator/issues/29.
Relate `ca - trfk - (karma - ca) - catalogue`, and make sure the karma URL displayed in catalogue is the ingress URL and not the k8s fqdn.
In tandem with:
- https://github.com/canonical/karma-k8s-operator/pull/36
[IPA] Add scheme to provide_ingress_requirements.
=> [IPA] Add scheme to provide_ingress_requirements

lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, src/charm.py, tests/scenario/utils.py
As part of our TLS work, we agreed to turn off `insecureSkipVerify` in all of our charms.
Set `insecureSkipVerify` to `False` in the default config.
Itest are failing because we need to fix first:
- https://github.com/canonical/prometheus-k8s-operator/issues/511
- https://github.com/canonical/grafana-k8s-operator/issues/249
=> set insecureSkipVerify to False

lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, lib/charms/traefik_route_k8s/v0/traefik_route.py, src/charm.py, tox.ini
Grafana, which uses traefik_route, is currently unable to tell if the ingress endpoint is http or https.
This PR adds a scheme arg, so that traefik could inform over relation data which scheme it is using.
In tandem with:
- https://github.com/canonical/traefik-route-k8s-operator/pull/41
- https://github.com/canonical/grafana-k8s-operator/pull/257
Drive-by fixes:
- [IPU] Abort provide_ingress_requirements if there is no relation. The same thing was already impl'd for IPA in #233.
Set scheme for traefik_route.
=> Set scheme for traefik_route

lib/charms/tempo_k8s/v0/charm_tracing.py, src/charm.py, tests/scenario/test_tracing_integration.py, tox.ini
following https://github.com/canonical/tempo-k8s-operator/pull/43, we replace the charm_instrumentation lib with charm_tracing (rename)
=> swapped charm_instrumentation with charm_tracing (charm lib rename)

README.md
No issue, just a minor nit in the `README.md`.
Replaces `jnsgruk/traefik` container image with `canonical/traefik`
N/A
N/A
=> docs: use canonical/traefik container image instead of jnsgruk/traefik

charmcraft.yaml, lib/charms/observability_libs/v0/cert_handler.py, lib/charms/tempo_k8s/v0/charm_tracing.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, src/charm.py, tests/manual/bundle_1_http.yaml, tests/manual/bundle_3_reverse_termination.yaml, tests/manual/bundle_4_tls_termination.yaml, tests/manual/bundle_5_tls_end_to_end.yaml
When using bare IPs, traefik fails to match to the "domain" and serves the default cert, which fails the TLS handshake.
Set the default cert to the external ca cert, so bare IPs work too.
In tandem with:
- https://github.com/canonical/observability-libs/pull/60
Refs:
- https://community.traefik.io/t/send-https-request-to-ip-address-not-matching-certificate-domain/15534
- https://doc.traefik.io/traefik/https/tls/#default-certificate
1. Deploy the traefik charm from this PR together with the bundle from https://github.com/canonical/cos-lite-bundle/pull/80
2. Curl the traefik IP from within one of the COS containers (e.g. prometheus): `curl -v 10.43.8.206 https://10.43.8.206/trfk-prometheus-0/api/v1/targets`.
Set default cert.
=> Set default cert

src/charm.py
The charm makes a large number of API calls to retrieve information about the IP address allocated to the K8S service; cache this information to reduce the number of calls made and speed up hook performance.
Improve the performance of hook executions
Cache response from K8S to reduce the amount of API calls made.
The traefik charm stands out as always the last to settle in Sunbeam deployments; hopefully this may improve this situation a bit.
https://microstack.run/docs -> "multi-node tutorial"
=> Reduce the number of API calls to K8S

src/charm.py
Fixes #257
By including the pebble ready in refresh events, we can prevent the juju override of turning it back into clusterIP
Juju on microk8s
Same as https://github.com/canonical/traefik-k8s-operator/issues/257 
-
=> Include throwing pebble ready in the refresh events of Kubernetes service patch

lib/charms/traefik_k8s/v2/ingress.py, tests/scenario/conftest.py, tests/scenario/test_ipa.py, tox.ini
Fixes #260 
Add an observer for relation-departed
code wrongly assumed relation-changed would be fired if a remote unit departed
added a unittest to validate the behaviour at `tests.scenario.test_ipa.test_traefik_remote_app_scaledown_from_2`
- fixed issue where urls from scaled-down remote units would be persisted in servers configuration
=> Fix issue with remote unit scale down

tests/interface/test_ingress.py, tests/scenario/test_ipa.py, tox.ini
Problems in Scenario and interface tests
- Using ops-scenario >= 5.3.1
- https://github.com/canonical/ops-scenario/pull/64 is merged so IndexError does not raise anymore. test_ipa.py needs to be updated.
- https://github.com/canonical/charm-relation-interfaces/pull/85 is merged. No need to use specific ingress-v2-json ingress branch.
After merging following PRs, the problems appeared in the tests and the tests are fixed accordingly.
-  https://github.com/canonical/ops-scenario/pull/64 
-  https://github.com/canonical/charm-relation-interfaces/pull/85
Run `tox` to validate that all tests are passing.
This PR aims to fix the problems which are happened after merging some PRs in the dependent external libraries.
=> Fix Interface and Scenario tests

lib/charms/traefik_k8s/v1/ingress.py, tox.ini
On module import, warn users of v1 ingress that the lib is deprecated and give instructions to bump to v2.
Only do that in the requirer wrapper's `__init__` because traefik still supports v1 and therefore also uses the module.
=> deprecate ingress v1

config.yaml, lib/charms/harness_extensions/v0/capture_events.py, lib/charms/oathkeeper/v0/forward_auth.py, metadata.yaml, src/charm.py, src/traefik.py, tests/integration/conftest.py, tests/integration/test_forward_auth.py, tests/integration/testers/forward-auth/charmcraft.yaml, tests/integration/testers/forward-auth/lib/charms/oathkeeper/v0/auth_proxy.py, tests/integration/testers/forward-auth/metadata.yaml, tests/integration/testers/forward-auth/requirements.txt, tests/integration/testers/forward-auth/src/charm.py, tests/unit/test_charm.py
This PR adds integration with Oathkeeper - the policy decision point in Identity and Access Proxy architecture, by supporting a new `forwardAuth` middleware.
In order to integrate Traefik into IAP, it must update routing rules for the applications that requested to be protected with the `ForwardAuth` middleware. Its definition must include headers and oathkeeper's decisions address.
This PR integrates traefik with oathkeeper with the use of `forward-auth` interface.
Oathkeeper provides Traefik with its decisions address, allowed return headers and application names that requested the IAP protection. This information is processed by Oathkeeper from `auth-proxy` relation.
Traefik updates the relation databag with app names it provides ingress for, so that Oathkeeper can compare the app …
=> Integrate with oathkeeper via `forward-auth` interface

lib/charms/traefik_k8s/v1/ingress_per_unit.py, requirements.txt, tests/integration/testers/forward-auth/lib/charms/oathkeeper/v0/auth_proxy.py
Fixes #285 
Rely on ops 2.10 behaviour that breaking relations don't show up in model.relations.
Unit/integration tests should do it.
- Fixed bug introduced by https://github.com/canonical/operator/pull/1091
=> compat with ops 2.10

src/charm.py
When relating tempo to traefik, if tempo does not reply with an otlp_http endpoint, traefik will look for a grpc one. 
However that's not been requested in `__init__` and so that raises an exception.
Remove the optional grpc path as we're not requesting it. Instead, rely on otlp_http being requested in `__init__`.
n/a
deploy traefik and relate to tempo
- minor bugfix on the tracing integration
=> do not ask for grpc endpoint since we're not requesting it

lib/charms/traefik_k8s/v2/ingress.py, tests/scenario/test_ingress_per_app.py, tests/unit/test_databag_model.py, tests/unit/test_ingress_lib.py, tests/unit/test_lib_per_app_provides.py, tests/unit/test_lib_per_app_requires.py, tox.ini
Fixes #307 
And it switches back strip-prefix and redirect-https and ip to be optional args.
Pack this charm, deploy this bundle and verify that there are no errors on the tempo-traefik handshake.
```yaml
bundle: kubernetes
tempo:
charm: tempo-k8s
scale: 1
constraints: arch=amd64
storage:
data: kubernetes,1,1024M
traefik:
charm: traefik-k8s
channel: edge
revision: 171
series: focal
resources:
traefik-image: 158
scale: 1
constraints: arch=amd64
storage:
configurations: kubernetes,1,1024M
trust: true
relations:
- - traefik:ingress
- tempo:ingress
```
=> fixed export by alias in pydantic v2 and ingress mandatory args

lib/charms/traefik_k8s/v2/ingress.py
This changed in https://github.com/canonical/traefik-k8s-operator/pull/286 -- Likely a mistake.
It's possible there is more to this, but this is just something I noticed in one of our downstream PRs.
Suspected documentation regression
Fix the typo.
https://github.com/canonical/traefik-k8s-operator/pull/286
None.
Fixed a documentation regression in the v2 ingress library
=> Fix version number in documentation

lib/charms/certificate_transfer_interface/v0/certificate_transfer.py, src/traefik.py
Due to python's tricky syntax, a hard to spot regression sneaked into #298:
The [redirections](https://doc.traefik.io/traefik/routing/entrypoints/#redirection) was placed in a tuple, and serialized as a list, whereas it is supposed to be a dict.
As a result, itests [fail](https://github.com/canonical/cos-lite-bundle/actions/runs/8348911023/job/22851889833) with `error: field not found, node: [0]`:
```
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "traefik" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-03-19T20:35:42Z INFO Most recent service output:
(...)
time="2024-03-19T20:35:36Z" level=warning msg="No domain found in rule PathPrefix(`/test-bundle-jf9n-prometheus-0`), the TLS options applied for this router will depend …
```
=> Fix redirections to match schema

charmcraft.yaml, lib/charms/observability_libs/v0/cert_handler.py, lib/charms/tls_certificates_interface/v3/tls_certificates.py, lib/charms/traefik_k8s/v2/ingress.py, requirements.txt, src/charm.py, tox.ini
Certificates generated by the charm don't include intermediates: https://github.com/canonical/httprequest-lego-k8s-operator/issues/93.
Fetch-lib and use the new `.chain_as_pem` method.
In tandem with:
- https://github.com/canonical/observability-libs/pull/82
=> Use entire chain for the server cert

src/charm.py
return none from server_cert if tls is disabled. Otherwise tracing will raise an OSError when it fails to find the cert at that path.
=> fix server_cert return type

src/charm.py, tests/integration/test_charm_route.py, tests/integration/testers/route/src/charm.py, tests/unit/test_route.py
After #325 we started to add provided `entryPoints` to the static config so that it was possible to route to traefik on custom entrypoints. However, trying to call the same port on juju application ip:${PORT} failed with `Connection refused`. Both in automated and manual tests we verified it by calling the unit's IP, not the external IP (which is later passed in tracing databags).
Open ServicePort for entrypoints that are provided via `traefik_route`.
I updated integration tests for `route`, you can run them with:
```
tox -re integration -- -k test_charm_route --keep-models
````
in order to have a working model you can test manually too. Remember though that the last test removes the relation so you'll need to re-relate tester charm with traefik.
=> Open ServicePort for entrypoints passed via static traefik_route

src/charm.py, src/traefik.py, tox.ini
`server_cert` returns `SERVER_CERT_PATH`, but the cert is only ever pushed to the workload container, never written to the charm container. Consequently charm tracing breaks with tls because the path doesn't exist.
Also, removed a pointless warning log.
when you push the cert to the workload container, also write it to the charm container
deploy with tls enabled and watch it burn because other things are broken with tls. But this is definitely an issue too.
=> fix issue with cert not present on charm container

src/charm.py
This PR refactors `_get_loadbalancer_status` function. 
This PR:
- Removes `return ingress_address.hostname` since the hostname (external hostname) is [configured through juju config](https://github.com/canonical/traefik-k8s-operator/blob/main/src/charm.py#L1064) so it is not necessary to retrieve that from K8s
- Remove unnecessary indentation.
Run tests
=> Refactor `_get_loadbalancer_status`

src/charm.py
Traefik was using `LogProxyConsumer` that fetches and uses promtail to gather logs. This can cause issues in airgapped environments where promtail binary might not be accessible.
Fixes canonical/prometheus-k8s-operator#580.
As we cannot move to `LogForwarder` yet (requires Juju 3.4+) and traefik's logs are already known not to show up in Loki at the moment, keep the `logging` integration for future use (see canonical/loki-k8s-operator#392) and no upgrade surprises in environments where that relation can already be present; however replace it with `LokiPushApiConsumer` that doesn't fetch promtail (and without configuration doesn't pass logs either).
Deploy the following bundle and verify promtail isn't present on charm container (`/tmp`) and workload container (`/etc`):
```
bundle: …
```
=> Use LokiPushApiConsumer not to fetch promtail

src/traefik.py
Traefik's workload version has a 'v' prefix, which is redundant under the "Version" column.
```
App           Version  Status  Scale  Charm                     Channel      Rev  Address         Exposed  Message
alertmanager  0.27.0   active      1  alertmanager-k8s          latest/edge  119  10.152.183.222  no       
ca                     active      1  self-signed-certificates  latest/edge  144  10.152.183.246  no       
catalogue              active      1  catalogue-k8s             latest/edge   43  10.152.183.108  no       
grafana       9.5.3    active      1  grafana-k8s               latest/edge  114  10.152.183.198  no       
loki          2.9.6    active      1  loki-k8s                  latest/edge  151  10.152.183.238  no       
prometheus    2.50.1   active      1 …
```
=> Drop 'v' prefix from workload version

src/charm.py
right now you get:
```
❯ j run trfk/0 show-proxied-endpoints                                                                                                                           
Running operation 1 with 1 task                                                                                                                                 
- task 2 on unit-trfk-0                                                                                                                                       
Waiting for task 2...                                                                                                                                           
14:11:28 failed to fetch proxied endpoints from provider <charms.traefik_k8s.v1.ingress.IngressPerAppProvider object at …
```
=> better error for proxied endpoints failure

pyproject.toml, src/traefik.py, tox.ini
Closes #314.
Disable the global `checknewversion` option in the static config.
I also added the `sendanonymoususage` (send anonymous usage) config option, leaving it to its default value of `True`. According to the ADR I linked, we should have a config option to turn it off, but I'm leaving that out of this PR :)
=> feat: disable checknewversion

tests/integration/test_forward_auth.py
forward-auth itest fails about 50% of the time.
It relies on event deferral, and by extension on the update-status interval.
Override the "inf" interval we set in our autouse fixture just for this test.
h/t @natalian98
=> Use 5m update-status hook interval for the auth test

src/charm.py, src/traefik.py, tests/interface/conftest.py, tests/scenario/conftest.py, tests/scenario/test_setup.py, tests/scenario/test_tracing_integration.py, tests/scenario/test_workload_version.py, tests/unit/test_charm.py, tests/unit/test_deep_merge.py, tests/unit/test_route.py, tests/unit/test_tls_certificates.py
Linting currently fails due to change in how ruff 0.6.x orders imports
Run `tox -e fmt`
=> fix: reorder imports for ruff 0.6.x

config.yaml, src/charm.py, src/traefik.py, tests/integration/test_basic_auth.py, tests/scenario/test_middlewares.py
This PR adds basic auth support for traefik.
This is an all-or-nothing, single-user basic implementation. In the future we might choose to extend it supporting per-route auth, as well as multi-user support.
Deploy traefik from this branch and relate it over any ingress, ingress-per-unit or traefik-route relation to another charm.
Go to https://www.transip.nl/htpasswd/ and enter some testing username/password pair. Copy the output string.
`juju config traefik basic_auth_user='<that string>'`
(make sure to escape any weird characters)
Now verify that you need to enter that user/password pair when trying to CURL or GET any urls proxied by traefik
=> basic auth support

lib/charms/traefik_k8s/v0/traefik_route.py, src/charm.py, tests/integration/conftest.py, tests/integration/spellbook/build_all_caches.py, tests/integration/testers/forward-auth/charmcraft.yaml, tests/integration/testers/ipa/charmcraft.yaml, tests/integration/testers/ipu/charmcraft.yaml, tests/integration/testers/route/charmcraft.yaml, tests/integration/testers/route/src/charm.py, tests/integration/testers/tcp/charmcraft.yaml
Contributes to fixing https://github.com/canonical/traefik-route-k8s-operator/issues/55 and https://github.com/canonical/traefik-k8s-operator/issues/379
- Publish `v0 traefik_route` library with `LIBPATCH=1` under `traefik_k8s`
- Change old references to `traefik_route_k8s` to `traefik_k8s`
- drive-by: Add retry to charm building + `pydantic-core` for rust compiler error
https://github.com/canonical/traefik-route-k8s-operator/pull/60
=> Publish `traefik_route` v0 library

lib/charms/traefik_k8s/v0/traefik_route.py
Previous PR tried to publish a new library `traefik_k8s.v0.traefik_route`, but using an ID for an existing library `traefik_route_k8s.v0.traefik_route`.
Retrieve unique ID for this new lib using `charmcraft create-lib traefik_route`
https://github.com/canonical/traefik-k8s-operator/pull/403
=> Fix `traefik_route` library ID

src/prometheus_alert_rules/unit_unavailable.rule
The TraefikIngressUnitIsUnavailable is very unreliable and triggers constantly on COS installs. It should wait for 5 minutes before firing the alert.
Add `for: 5m` to the alert rule.
None really
Traefik alert rules are now more stable.
=> Change alert rule to be for 5 minutes

src/charm.py, tests/unit/test_route.py
Fixes #425 
Skip the generation of tls dynamic config in traffic when passthrough is set
When `tls.passthrough: true` is set for a route, Traefik forwards the raw TLS traffic directly to the backend service without terminating the TLS connection.
This means Traefik doesn't need to handle certificates, nor does it need additional TLS configuration 
1- juju deploy traefik-k8s 
2- juju deploy [wazuh-server-operator](https://github.com/canonical/wazuh-server-operator)
3- juju relate traefik-k8s wazuh-server-operator
4- Fetch traefik's dynamic config and validate no tls entry is created and main entry has `tls.passthrough: true`
=> Skip tls config when passthrough is enabled

tests/scenario/conftest.py, tests/scenario/test_tracing_integration.py
adds a call into charm_logging_disabled contextmgr from the conftest.py fixture for traefik.
=> cleanup logging output during scenario tests due to charm-tracing being enabled by default

src/charm.py, tests/scenario/test_ingress_per_unit.py, tests/scenario/test_status.py
Fully fixes #261
Go in to blocked state when `routing_mode` is set to "subdomain" but `external_hostname` is not set.
* Deploy charm
* Set `routing_mode` to `subdomain`
* Observe unit status
=> Subdomain external hostname

lib/charms/traefik_k8s/v0/traefik_route.py, src/charm.py, tests/unit/test_route.py
Fixes #430
For every route, `traefik` created a duplicate route `ROUTENAME-tls` for the same rule and service but with additional TLS configuration. Both applied to the same rule and thus conflict, and the new `ROUTENAME-tls` route takes precedence over the original `ROUTENAME` because its name is longer. 
- **New Parameter:** Introduce a new boolean argument `raw` in the interface.
- **Conditional Behavior:**  
- When `raw` is set to `True`, Traefik will **only** append TLS routes to HTTP routes.
- TLS routes for non-HTTP protocols will not be generated, preventing the duplicate `ROUTENAME-tls` routes.
**Tandem PR**: https://github.com/canonical/grafana-k8s-operator/pull/391
=> Traefik appends a `tls` route even when `tls` routes are explicitly provided

src/charm.py
Potentially fix the issue where TLS communication to Traefik fails in environments where the Loadbalancer IP can be resolved back to a hostname on the machine running the workloads.
Potentially fix https://github.com/canonical/traefik-k8s-operator/issues/347
Fixes #461
@PietroPasotti to confirm.
If an IP address can be resolved back to a hostname, return both the hostname as well as the IP address to be used in the certificate SANS. The reason is that charms related to Traefik over ingress will communicate with Traefik via this IP address and thus it should be contained in the server certificate SANS.
=> Add the IP address of the resolved hostname to the certificate SANS

tests/integration/test_forward_auth.py
IAM-610
Update tests, the `dev` flag is not needed with the latest version of oathkeeper
Closes https://github.com/canonical/oathkeeper-operator/issues/46
=> Disable  flag in forward_auth tests

metadata.yaml
Solutions QA is testing all charms over all relations. Currently traefik gets pulled into many deployments . This MR reduces the footprint of automatically generated bundles containing traefik based on the optional relations flag.
Set the optional flag to true for all requires.
https://canonical-charmcraft.readthedocs-hosted.com/en/stable/reference/files/metadata-yaml-file/#requires
N/A
N/A
=> set optional to true for all requires

lib/charms/observability_libs/v1/cert_handler.py, tests/integration/helpers.py, tests/integration/test_charm_health.py, tests/integration/test_charm_ipa.py, tests/integration/test_charm_ipu.py, tests/integration/test_charm_route.py, tests/integration/test_charm_tcp.py, tests/integration/test_forward_auth.py, tests/integration/test_tcp_ipa_compatibility.py, tests/integration/test_tcp_ipu_compatibility.py
Rebase of the changes recently pushed to revision 238 for issue #491.
In order to be backwards compatible, we separate the chain (which is a string of the form `"{cert}\n\n{cert}\n\n...{cert}"`). We then check to see if the first element of the chain is the same as the leaf cert. If it is not we reverse the chain.
This does not cover the case of any poorly ordered chain. It only covers the case of reverse order that is sent by old versions of `self-signed-certificates`. This is okay as providers of the interface should be send in order. We are only catching a specific known wrong ordering and we will remove this check after sufficient time has passed. This means that if a different provider charm sends the chain in the wrong order, there is a chance we can find the error.
=> Rebase reverse chain fix

lib/charms/traefik_k8s/v2/ingress.py
In the IngressRequirerPerApp class of the traefik library, the doc strings mention that the URL provided can be used to reach the **current unit** which is misleading as the URL is common for the application and is load balanced across the units.
This PR changes the doc string slightly to fix this issue.
=> docs: minor doc string fixes for traefik lib

src/charm.py, src/traefik.py, tests/unit/test_tls_certificates.py
fixes #504, fixes #480, fixes #514
Add a `try/except` guard to the `remove_path` call when removing old certificates.
Add a cleanup method for TLS configuration.
=> ISD-4203 guard against container.remove_file and add cleanup logic for TLS
