canonical/traefik-k8s-operator

src/charm.py, tests/unit/test_charm.py
=> Ensure the configuration folder exists before Traefik starts

lib/charms/traefik_k8s/v0/ingress_per_unit.py
Cleaning up the code (some duplication)
Fixed bad model re _supported_versions legacy.
The CI should handle it
- Cleaned up IPU code
- Fixed error in data model
=> inconsistencies in IPU fixed

lib/charms/traefik_k8s/v0/ingress.py, src/charm.py, tests/integration/test_charm_ipa.py, tests/integration/test_charm_ipu.py
Fixed a bug in wipe codepath
Fixes #55 
- Fixed bug (SDI leftover)
=> fixed two bugs with wipe and route

.github/workflows/pull-request.yaml, lib/charms/traefik_k8s/v0/ingress_per_unit.py, tox.ini
Fixes #54 
Typed ipu
Added tox and git tests
`tox -vve static-ipu`
- typed ingress-per-unit
=> Typing ipu

lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, tox.ini
Some lingering v0 references in the docstrings for ipa/ipu
=> ipa and ipu v1 docfix

lib/charms/traefik_k8s/v1/ingress.py, tests/unit/test_lib_per_app_requires.py, tests/unit/test_lib_per_unit_requires.py
Added a couple of unittests to verify the ingress_requirements validation behaviour.
=> validator tests for ipa and ipu

.github/workflows/promote.yaml, .github/workflows/pull-request.yaml, .github/workflows/release-edge.yaml
This should fix the released revision name
=> Update charming-actions to 2.0.0-rc

requirements.txt
=> bumped ops version to 1.5.2

lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, src/charm.py, tests/unit/test_charm.py, tests/unit/test_lib_per_app_provides.py, tests/unit/test_lib_per_app_requires.py, tests/unit/test_lib_per_unit_provides.py, tests/unit/test_lib_per_unit_requires.py
Fixes #45 
All existing tests have been parametrized to account for the new variable.
- added strip_prefix=False option.
=> Path prefix strip option

lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py
=> bump library patch

lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, src/charm.py
Path prefix stripping config currently goes in the wrong place. This PR resolves that.
=> change the output format of the path prefix stripping

tests/unit/test_charm.py, tox.ini
Fix the unit test failures caused by recent changes.
=> fix unit tests

src/prometheus_alert_rules/reload_failure.rule
Missing commit from #115 :facepalm: suggeted by @sed-i in [this comment](https://github.com/canonical/traefik-k8s-operator/pull/115#discussion_r1061665076)
=> expr improved

tests/integration/spellbook/build_all_caches.py, tests/integration/spellbook/cache.py
Did charmcraft pack's output just change? #117 was merged too hastily and I realized the CI was broken.
=> Fix spellbook cache charmcraft pack error

lib/charms/observability_libs/v0/juju_topology.py, tox.ini
Use 3.1/edge to work around the unit termination issue. update-lib.
=> Use new Juju for CI

tests/unit/test_charm.py
=> Update unit tests for Pebble changes

src/charm.py
On slow machines, relation events that end up calling pebble may be emitted before pebble is ready.
Add a `can_connect` guard.
Fixes #155.
NTA.
Retry deploying the bundle (with a local charm from this PR) on a GH runner. Or "test in production".
Add `can_connect` guard to certs available event.
=> Add `can_connect` guard to certs available event

tests/scenario/test_workload_version.py, tox.ini
This PR adds a scenario test around `set_workload_version`.
=> Add scenario test for workload version

lib/charms/traefik_k8s/v2/ingress.py, tests/unit/test_databag_model.py
Allow extra fields in ingress relation databags
=> removed no-extra-fields req on ingress v2

lib/charms/traefik_k8s/v1/ingress_per_unit.py
The `scheme: lambda ...` IPU constructor arg does not address custom events from other relation (e.g. certificates broken), because IPU requirer only observes and acts on its own events: a change of scheme in between charm re-inits has no effect on its own. This could potentially have been address with "refresh_events" arg, but since ingress is fundamental, this could have introduced a circular dependency.
Add a `scheme` arg to `provide_ingress_requirements` so lib user can call it manually in the custom event observer.
- Fixes #231.
- Addresses https://github.com/canonical/prometheus-k8s-operator/issues/516
**[Y-statement](https://adr.github.io/#sustainable-architectural-decisions)**: In the context of custom events, facing outdated scheme on certificates-relation-broken, we decided to …
=> Add scheme arg to `provide_ingress_requirements`

requirements.txt, tests/scenario/test_ingress_per_app.py, tests/scenario/test_ingress_tls.py, tests/scenario/test_ingress_v1_backwards_compat/test_ingress_per_app_v1.py, tests/scenario/test_ingress_v1_backwards_compat/test_ingress_tls_v1.py, tests/scenario/test_ingress_v1_backwards_compat/test_middlewares_v1.py, tests/scenario/test_middlewares.py, tests/scenario/test_tracing_integration.py, tox.ini
branch to show @sed-i how to fix scenario 5 compat
=> compat with scenario 5

.gitignore, lib/charms/traefik_k8s/v2/ingress.py, tests/integration/testers/forward-auth/lib/charms/oathkeeper/v0/auth_proxy.py, tests/unit/test_databag_model.py
This PR makes the ingress library compatible with pydantic v1 and pydantic v2.
=> ingress lib support for pydantic v2

lib/charms/traefik_k8s/v2/ingress.py, tests/scenario/test_ipa.py
something went wrong in the release pipeline for ingress v2.9; apparently the minor already existed.
this bumps to v2.10 hoping to fix any inconsistencies
=> vbump for ingress lib

lib/charms/traefik_k8s/v1/ingress_per_unit.py
=> fixed issue in ipu

src/traefik.py
Configures traefik to redirect by default http to https if tls is enabled.
Replaces #246 
Fixes #177
=> http->https redirect

config.yaml, src/charm.py, tests/scenario/test_ingress_tls.py
#294
Added config options for TLS.
* Deploy cos-lite
* Set TLS config options in traefik
* Observe that TLS is working properly
(A good way to get working certs is to first relate to self-signed-certificates operator, then use the ones it generates)
=> Tls config values

src/charm.py, src/traefik.py
Fixes #352.
Apply the same logic to all routers, including TLS routers.
Bundle traefik together with `edge` Tempo and peek at a generated route file inside Traefik container.
=> TLS for all paths of traefik_route

lib/charms/loki_k8s/v1/loki_push_api.py, src/charm.py
Upgrade `loki_push_api` to new major version. Fixes #333, related to canonical/prometheus-k8s-operator#580.
=> Upgrade loki_push_api to v1

src/charm.py
remove call to deprecated tracing.otlp_http_protocol
=> remove call to deprecated tracing lib api

lib/charms/observability_libs/v1/kubernetes_service_patch.py, tox.ini
In tandem with https://github.com/canonical/observability-libs/pull/104
=> Tandem k8s svc patch

tests/integration/helpers.py, tests/integration/test_workload_tracing.py, tox.ini
Integration tests were missing for workload tracing in Traefik.
Add a test case for testing workload tracing.
Run the integration tests.
=> Add workload tracing integration tests

.github/workflows/pull-request.yaml
Fix this failing CI:
- https://github.com/canonical/traefik-k8s-operator/actions/runs/15592140424/job/43913712895?pr=488#step:8:1378
=> Update pull-request.yaml to pin `juju-channel` to `3.6/stable`

terraform/outputs.tf
Some outputs in the ouputs.tf were outdated, this updates them.
=> fix: TF outputs.tf

.github/.jira_sync_config.yaml, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement_proposal.yml, .github/pull_request_template.md
Align templates and Jira sync bot with the team standards
=> Align with PFE standards

lib/charms/traefik_k8s/v0/traefik_route.py, lib/charms/traefik_k8s/v1/ingress.py, lib/charms/traefik_k8s/v2/ingress.py
Bump lib version after refactoring
=> Bump ingress_v1 lib versions
